### ISSUE TITLE
[Suggestions] Coffee Lake (9th Gen) on Z390

### ISSUE THREAD

**Issue by MSTRKKRFT** [ocwebutils/rules#4]
Hi, 

I just tried your sanity checker, great to see one back for last revisions of OC, thanks for your work! 

My config is : i7-9700K + z390 Aorus Elite + RX 6600 XT (iGPU as headless)

When checking my config.plist, here are a few mistakes on the results : 

**BOOTER**
_Type: **Warning** / Booter.Quirks.**ProtectUefiServices** : must be enabled on X370 boards_
> My system is z390 and needs this quirk Enabled, so it should maybe not be a warning but an Info instead. Or maybe add a motherboard selection in the tool, but I can imagine it's not the same amount of work. 

**KERNEL**
_Type: **Warning** / Kernel.Quirks.**AppleCpuPmCfgLock** & Kernel.Quirks.**AppleXcpmCfgLock** : should be enabled if you have CFG-Lock enabled_
> I have CFG-Lock disabled in BIOS so I don't need these quirks, maybe you could set them to info instead of warning.

_Type: **Warning** / Kernel.Quirks.**DisableIoMapper** : should be enabled if VT-D is enabled in BIOS_
> Same here, I have VT-D disabled in BIOS so I don't need this quirks, maybe you could set them to info instead of warning.  

Have a great day :) 
MSTRKKRFT

**Comment by ririxichan** [comment]
Okay,
I looked into your suggestions and that's what I think about them:
As you probably saw, we have 3 types of return value, `info`, `warning` and `error`

- `Info` is used for values that are not that important e.g. Debug stuff like `AppleDebug` 
- `Warning` is used for values that are actually important but shouldn't be thrown as errors since it's not always a case e.g. `DisableIoMapper`
- `Error` is used for values that actually *need* to be enabled for you to boot e.g. `AvoidRuntimeDefrag`

So, I don't think that would be good to change rules that you mentioned to `info` type
However, I noticed that `ProtectUefiServices` throws `X370` instead of `Z370` which is my bad and will be fixed in next rules update.
